# Generated by Django 5.0.6 on 2024-06-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('email_verified_at', models.DateField()),
                ('is_active', models.BooleanField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('activity_sector', models.CharField(max_length=50)),
                ('rccm', models.IntegerField(max_length=20)),
                ('turnover', models.IntegerField(max_length=20)),
                ('web_site', models.CharField(max_length=50)),
                ('manager_last_name', models.CharField(max_length=30)),
                ('manager_first_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=20)),
                ('sold', models.IntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
