# Generated by Django 5.0.6 on 2024-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partners',
            name='rccm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partners',
            name='sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partners',
            name='turnover',
            field=models.IntegerField(),
        ),
    ]
