# Generated by Django 5.0.6 on 2024-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_partners_phone_alter_partners_rccm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('status', models.CharField(default='En cours')),
            ],
        ),
        migrations.CreateModel(
            name='Phonebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('name', models.CharField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
