# Generated by Django 5.0.6 on 2024-06-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_advertising_phonebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonebookAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advertising')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonebooks')),
            ],
        ),
    ]
