# Generated by Django 5.0.6 on 2024-06-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phonebookadvertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocationtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PhonebookAllocationtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allocationtypes')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.phonebooks')),
            ],
        ),
    ]
