# Generated by Django 5.0.6 on 2024-06-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_phonebooks_partner_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partners')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('status', models.CharField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partners')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('status', models.CharField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partners')),
            ],
        ),
    ]
