# Generated by Django 5.0.6 on 2024-06-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deposits_newsletters_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAllocationtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount', models.IntegerField()),
                ('allocationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.allocationtypes')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments')),
            ],
        ),
        migrations.CreateModel(
            name='PartenerNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newsletters')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.partners')),
            ],
        ),
    ]
