# Generated by Django 5.0.6 on 2024-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_departments_departmentallocationtypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
